"""Build a minimal RNAAS portal-submission source bundle from the canonical source."""

import argparse
import hashlib
import json
import shutil
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
AUDIT_PATH = ROOT / "outputs" / "stage4_rnaas_release_audit.json"
OUTPUT_DIR = ROOT / "outputs" / "stage4_rnaas_submission"
ZIP_PATH = ROOT / "outputs" / "toi3492_rnaas_submission.zip"
FILES = (
    "toi3492_rnaas.tex",
    "references.bib",
    "figures/toi3492_120s_reference_fold.png",
)


def _sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--replace", action="store_true",
                        help="Replace only a bundle generated by this script.")
    args = parser.parse_args()
    audit = json.loads(AUDIT_PATH.read_text(encoding="utf-8"))
    if audit.get("status") != "PASS":
        raise RuntimeError("RNAAS release audit must pass before packaging")
    if OUTPUT_DIR.exists() or ZIP_PATH.exists():
        if not args.replace:
            raise FileExistsError("refusing to overwrite an existing RNAAS submission bundle")
        if OUTPUT_DIR.exists():
            shutil.rmtree(OUTPUT_DIR)
        if ZIP_PATH.exists():
            ZIP_PATH.unlink()
    manifest = {"schema_version": "1.0", "files": {}}
    for relative_path in FILES:
        source = ROOT / relative_path
        target = OUTPUT_DIR / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        manifest["files"][relative_path] = {
            "sha256": _sha256(target),
            "size_bytes": target.stat().st_size,
        }
    manifest_path = OUTPUT_DIR / "MANIFEST.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    with zipfile.ZipFile(ZIP_PATH, "x", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(OUTPUT_DIR.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(OUTPUT_DIR).as_posix())
    with zipfile.ZipFile(ZIP_PATH) as archive:
        if sorted(archive.namelist()) != sorted([
                "MANIFEST.json", "references.bib", "toi3492_rnaas.tex",
                "figures/toi3492_120s_reference_fold.png",
        ]):
            raise RuntimeError("RNAAS bundle contents differ from the canonical source list")
        if archive.testzip() is not None:
            raise RuntimeError("RNAAS bundle CRC verification failed")
    print("Wrote {}".format(ZIP_PATH))


if __name__ == "__main__":
    main()
