"""Reproducibility freeze and release packager.

``exonym freeze`` builds a frozen reproducibility bundle under
``candidate/<id>/releases/<version>/`` containing pinned dependency locks,
container image definitions, and a content-addressed manifest.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from .workspace import CandidateWorkspace, METADATA_FILENAME

DOCKERFILE_TEMPLATE = """# EXONYM reproducibility image
# Generated by exonym freeze for {{CANDIDATE_ID}}.
FROM python:3.9-slim
WORKDIR /work
COPY requirements.lock.txt /work/requirements.lock.txt
RUN pip install --no-cache-dir -r /work/requirements.lock.txt
COPY . /work/
CMD ["python", "-c", "import exonym; print(exonym.__version__)"]
"""

APPTAINER_TEMPLATE = """# EXONYM reproducibility definition
# Generated by exonym freeze for {{CANDIDATE_ID}}.
Bootstrap: docker
From: python:3.9-slim

%post
    apt-get update && apt-get install -y --no-install-recommends git
    pip install --no-cache-dir -r /work/requirements.lock.txt

%runscript
    exec python -c "import exonym; print(exonym.__version__)"
"""

ENVIRONMENT_TEMPLATE = """name: exonym-freeze-{{CANDIDATE_ID}}
channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - pip
  - pip:
    - {pip_entries}
"""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _git_commit(repository_root: Path) -> str:
    try:
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repository_root,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except OSError:
        pass
    return "unknown"


def _default_version() -> str:
    return "release-" + _now().replace(":", "").replace("-", "")[:15]


def freeze(workspace: CandidateWorkspace, version: Optional[str] = None) -> Path:
    """Build the reproducibility bundle and return its directory."""
    version = version or _default_version()
    release_dir = workspace.path / "releases" / version
    if release_dir.exists():
        raise FileExistsError("release already exists: {0}".format(release_dir))
    release_dir.mkdir(parents=True)

    repository_root = workspace.repository_root
    lock_source = repository_root / "requirements-lock.txt"
    if not lock_source.is_file():
        raise FileNotFoundError("root requirements-lock.txt not found: {0}".format(lock_source))
    shutil.copyfile(lock_source, release_dir / "requirements.lock.txt")

    pip_entries = []
    for line in lock_source.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            pip_entries.append('      "{0}"'.format(line))
    environment = (
        ENVIRONMENT_TEMPLATE.replace("{{CANDIDATE_ID}}", workspace.candidate_id)
        .replace("{pip_entries}", ",\n".join(pip_entries))
    )
    (release_dir / "environment.lock.yml").write_text(environment, encoding="utf-8")

    dockerfile = DOCKERFILE_TEMPLATE.replace("{{CANDIDATE_ID}}", workspace.candidate_id)
    (release_dir / "Dockerfile").write_text(dockerfile, encoding="utf-8")
    apptainer = APPTAINER_TEMPLATE.replace("{{CANDIDATE_ID}}", workspace.candidate_id)
    (release_dir / "Apptainer.def").write_text(apptainer, encoding="utf-8")

    metadata_path = workspace.path / METADATA_FILENAME
    files: List[Dict] = []
    for path in sorted(release_dir.rglob("*")):
        if path.is_file():
            files.append(
                {
                    "path": path.relative_to(release_dir).as_posix(),
                    "size_bytes": path.stat().st_size,
                    "sha256": _sha256(path),
                }
            )
    manifest = {
        "schema": "exonym-freeze-1",
        "version": version,
        "candidate_id": workspace.candidate_id,
        "frozen_at": _now(),
        "git_commit": _git_commit(repository_root),
        "candidate_json_sha256": _sha256(metadata_path),
        "files": files,
    }
    (release_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return release_dir
